-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 16:48:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contatos`;
CREATE TABLE `contatos` (
  `idContato` int NOT NULL AUTO_INCREMENT,
  `Nome` varchar(45) NOT NULL,
  `Numero` varchar(45) NOT NULL,
  `Foto` varchar(45) NOT NULL,
  `createdAt` varchar(45) DEFAULT NULL,
  `updatedAt` char(5) DEFAULT NULL,
  PRIMARY KEY (`idContato`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoritos`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `favoritos`;
CREATE TABLE `favoritos` (
  `idFavoritos` int NOT NULL AUTO_INCREMENT,
  `numero_favoritos` int NOT NULL,
  `Contato_idContato` int NOT NULL,
  PRIMARY KEY (`idFavoritos`,`Contato_idContato`),
  KEY `fk_Favoritos_Contato_idx` (`Contato_idContato`),
  CONSTRAINT `fk_Favoritos_Contato` FOREIGN KEY (`Contato_idContato`) REFERENCES `contatos` (`idContato`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloqueados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bloqueados`;
CREATE TABLE `bloqueados` (
  `idBloqueados` int NOT NULL AUTO_INCREMENT,
  `numero_bloqueados` varchar(45) DEFAULT NULL,
  `Contato_idContato` int NOT NULL,
  PRIMARY KEY (`idBloqueados`,`Contato_idContato`),
  KEY `fk_Bloqueados_Contato1_idx` (`Contato_idContato`),
  CONSTRAINT `fk_Bloqueados_Contato1` FOREIGN KEY (`Contato_idContato`) REFERENCES `contatos` (`idContato`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
